# Generated by Django 4.2.6 on 2023-10-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autenticaciones',
            fields=[
                ('id_Autenticacion', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('id_Autenticacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covenbiins.autenticaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id_Rating', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('calificacion', models.IntegerField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covenbiins.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id_Inmueble', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipoInmueble', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covenbiins.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_Citas', models.BigAutoField(primary_key=True, serialize=False)),
                ('horaCita', models.DateTimeField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AsesorFk', to='covenbiins.usuarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioFk', to='covenbiins.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id_Aprobacion', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('copiaCedula', models.CharField(max_length=50)),
                ('certificadoLibertad', models.CharField(max_length=50)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covenbiins.usuarios')),
                ('id_Inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covenbiins.inmuebles')),
            ],
        ),
    ]
