# Generated by Django 4.2.6 on 2023-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='imagen',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
