# Generated by Django 4.2.6 on 2023-10-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0002_alter_inmuebles_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobaciones',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.usuarios'),
        ),
        migrations.AlterField(
            model_name='aprobaciones',
            name='id_Inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.inmuebles'),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.usuarios'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_Autenticacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.autenticaciones'),
        ),
    ]
