# Generated by Django 4.2.6 on 2023-10-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0003_alter_aprobaciones_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipoUsuario',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Asesor Legal'), (3, 'Vendedor'), (4, 'Comprador')], default=4),
        ),
    ]
