# Generated by Django 4.2.6 on 2023-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0004_alter_usuarios_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/default.png', null=True, upload_to='fotos'),
        ),
    ]
