# Generated by Django 4.2.7 on 2024-01-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0006_remove_usuarios_id_autenticacion_usuarios_contrasena_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autenticaciones',
        ),
    ]
