# Generated by Django 4.2.6 on 2024-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0007_delete_autenticaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='imagen',
            field=models.ImageField(blank=True, default='fotos/default.png', null=True, upload_to='fotos_inmuebles'),
        ),
    ]
