# Generated by Django 4.2.7 on 2024-02-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0009_citas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/default.jpeg', null=True, upload_to='fotos'),
        ),
    ]
