# Generated by Django 4.2.7 on 2024-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0010_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='area',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='banos',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='habitaciones',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
