# Generated by Django 4.2.6 on 2024-02-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0013_alter_inmuebles_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
