# Generated by Django 4.2.6 on 2024-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0014_delete_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='estrato',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
