# Generated by Django 4.2.6 on 2024-02-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0015_inmuebles_estrato_alter_inmuebles_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_Lista', models.BigAutoField(primary_key=True, serialize=False)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.usuarios')),
                ('id_Inmueble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.inmuebles')),
            ],
        ),
    ]
