# Generated by Django 4.2.6 on 2024-02-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0017_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='cedula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covenbiins.usuarios'),
        ),
    ]
