# Generated by Django 4.2.6 on 2024-03-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0018_informe_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Usado'), (2, 'Nuevo')], default=1),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
