# Generated by Django 4.2.6 on 2024-03-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covenbiins', '0019_inmuebles_categoria_inmuebles_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=254)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios_fk2', to='covenbiins.usuarios')),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios_fk1', to='covenbiins.usuarios')),
            ],
        ),
    ]
